### ISSUE TITLE
Allow negative temperatures in BrewPi to make Ice

### ISSUE THREAD

**Issue by KarlR83** [BrewPi/brewpi-www#49]
I'm using a chest freezer with RaspberryPi. I'm trying to make some ice for brewday (cooling down the hot wort quickly). But it seems BrewPi doesn't allow me to set negative °C temperatures. This feature/profile should be added, so one can use his freezer as normal, even with Brewpi.

**Comment by elcojacobs** [comment]
Have you changed the absolute minimum in advanced settings to -16?
-16 is the lowest temperature we can store in our internal temperature format.

**Comment by KarlR83** [comment]
Oh I didn't knew this. Tried and seems to work. So you can close the issue
