### ISSUE TITLE
Cannot access brewpi with browser but system say it is runing

### ISSUE THREAD

**Issue by astrawa** [BrewPi/brewpi-www#58]

**Comment by astrawa** [comment]
I am running brewpi on a raspberrypi. I typed in the pi IP address: http://192.168.1.66 and get error 404 not found- Apache/2.4.10 (Raspbian) Server at 192.168.1.66 Port 80
Then I type in the sudo command to start brewpi and get the message
---
pi@raspberrypi:~ $ sudo -u brewpi python /home/brewpi/brewpi.py
Conflict: same config file as another BrewPi instance already running.
 Dec 30 2015 20:08:48   Another instance of BrewPi is already running, which will conflict with this instance. This instance will exit.
---

I am at a loss as how to proceed. Please help.

AWS

**Comment by astrawa** [comment]
I am following the next step, trying to program without the web interface using the command
pi@raspberrypi:~ $ sudo python /home/brewpi/programArduinoFirstTime.py
And I get the message:
Usage: /home/brewpi/programArduinoFirstTime.py <config file full path>

Looking into the programArduinoFirstTime.py file, the code seems to be looking for a config file.I think the documentation should include a second argument to /home/brewpi/settings/config.cfg.

Using this argument the program runs BUT appears to hang at "Checking old version before programming"

**Comment by astrawa** [comment]
The traceback from running programArduinoFirstTime is
pi@raspberrypi:~ $ sudo python /home/brewpi/programArduinoFirstTime.py
Usage: /home/brewpi/programArduinoFirstTime.py <config file full path>

**Comment by elcojacobs** [comment]
The brewpi web interface and python script are separate things.
Please use our install script from brewpi-tools to install both.

Use the web interface to uploade the appropriate hex file to the Arduino, which you can find here:

https://github.com/BrewPi/firmware/releases/tag/0.2.10

**Comment by astrawa** [comment]
Thanks for responding. I followed your advice and reinstalled, but when I try to access the web interface by entering http://192.168.1.66 I get the same error:
The requested URL / was not found on this server.
Apache/2.4.10 (Raspbian) Server at 192.168.1.66 Port 80

The traceback for the install did not show any errors. Here it is.
pi@raspberrypi:~ $ sudo brewpi-tools/install.sh

Checking for Internet connection...
Success!

To accept the default answer, just press Enter.
The default is capitalized in a Yes/No question: [Y/n]
or shown between brackets for other questions: [default]

Checking whether this script is up to date...

fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/home/pi/brewpi-tools is up-to-date.

Disk usage is 63%, free disk space is 2.3G. Enough to install BrewPi

The time is currently set to Fri  1 Jan 15:53:00 PST 2016. Is this correct? [Y/n]y

*** This script will first ask you where to install the brewpi python scripts and the web interface
Hitting 'enter' will accept the default option in [brackets] (recommended).

Any data in the following location will be ERASED during install!
Where would you like to install BrewPi? [/home/brewpi]: y
Installing script in /home/brewpi
Install directory is NOT empty, are you SURE you want to use this path? [y/N] y
Ok, we warned you!

Any data in the following location will be ERASED during install!
What should be the path to your web directory for brewpi? [/var/www]: y
Installing web interface in /var/www
Web directory is NOT empty, are you SURE you want to use this path? [y/N] y
Ok, we warned you!

***** Installing/updating required packages... *****

Reading package lists... Done
Building dependency tree       
Reading state information... Done
apache2 is already the newest version.
build-essential is already the newest version.
git-core is already the newest version.
libapache2-mod-php5 is already the newest version.
php5 is already the newest version.
php5-cgi is already the newest version.
php5-cli is already the newest version.
php5-common is already the newest version.
python-dev is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.

***** Installing/updating required python packages via pip... *****

Downloading/unpacking pyserial from https://pypi.python.org/packages/source/p/pyserial/pyserial-3.0.tar.gz#md5=f94bc6e141d60f17edc7bf8757c4d922
  Downloading pyserial-3.0.tar.gz (133kB): 133kB downloaded
  Running setup.py (path:/tmp/pip-build-rjO0zN/pyserial/setup.py) egg_info for package pyserial
    
Requirement already up-to-date: psutil in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: simplejson in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: configobj in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: gitpython in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from configobj)
Requirement already up-to-date: gitdb>=0.6.4 in /usr/local/lib/python2.7/dist-packages (from gitpython)
Requirement already up-to-date: smmap>=0.8.5 in /usr/local/lib/python2.7/dist-packages (from gitdb>=0.6.4->gitpython)
Installing collected packages: pyserial
  Found existing installation: pyserial 2.7
    Uninstalling pyserial:
      Successfully uninstalled pyserial
  Running setup.py install for pyserial
    changing mode of build/scripts-2.7/miniterm.py from 644 to 755
    
    changing mode of /usr/local/bin/miniterm.py to 755
Successfully installed pyserial
Cleaning up...

***** Done processing BrewPi dependencies *****


***** Creating and configuring user accounts... *****
User 'brewpi' already exists, skipping...

***** Checking install directories *****
/home/brewpi already exists
Script install directory is NOT empty, backing up to this users home dir and then deleting contents...
/var/www already exists
Web directory is NOT empty, backing up to this users home dir and then deleting contents...

***** Downloading most recent BrewPi codebase... *****
Cloning into '/home/brewpi'...
remote: Counting objects: 1557, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 1557 (delta 32), reused 0 (delta 0), pack-reused 1501
Receiving objects: 100% (1557/1557), 503.45 KiB | 322.00 KiB/s, done.
Resolving deltas: 100% (933/933), done.
Checking connectivity... done.
Cloning into '/var/www'...
remote: Counting objects: 1865, done.
remote: Total 1865 (delta 0), reused 0 (delta 0), pack-reused 1865
Receiving objects: 100% (1865/1865), 1.08 MiB | 402.00 KiB/s, done.
Resolving deltas: 100% (1174/1174), done.
Checking connectivity... done.

***** Running fixPermissions.sh from the script repo. *****

***** Fixing file permissions for /var/www *****

***** Fixing file permissions for /home/brewpi *****

***** Running updateCron.sh from the script repo. *****

***** Updating cron for the brewpi user... *****

no crontab for brewpi
Checking entry for brewpi ...
Done checking entry brewpi ...
Checking entry for wifichecker ...
Done checking entry wifichecker ...
Restarting cron
[ ok ] Restarting cron (via systemctl): cron.service.
Done installing BrewPi!

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Review the log above for any errors, otherwise, your initial environment install is complete!

You are currently using the password 'brewpi' for the brewpi user. If you wish to change this, type 'sudo passwd brewpi' now, and follow the prompt

To view your BrewPi web interface, enter http://192.168.1.66   into your web browser

Happy Brewing!

**Comment by elcojacobs** [comment]
1. Your install script reports something about not being a git repository. You probably downloaded it as zip instead of doing a git clone. It was not able to update itself which would have prevented this problem.

2. You installed brewpi to /var/www. If you are on debian jessie, the default web root is /var/www/html. You need to change the documentroot in /etc/apache2/sites-available/000-default.conf to /var/www/ instead of /var/www/html

3. Please use GitHub issues only for reporting bugs, not for requesting support.
